pipline

diff --git a/.github/workflows/db_migration.yml b/.github/workflows/db_migration.yml
--- a/.github/workflows/db_migration.yml
+++ b/.github/workflows/db_migration.yml
@@ -28,40 +28,38 @@ jobs:
           aws s3 cp init.py s3://540034108652-devops-scripts/init.py --region eu-north-1
           echo "✅ Files Uploaded to bucket.."
 
-      # - name: Initializing Database on RDS using Ec2
-      #   id: init
-      #   run: |
-      #     CMD_ID=$(aws ssm send-command \
-      #       --targets "Key=tag:App,Values=flask" \
-      #       --document-name "AWS-RunShellScript" \
-      #       --parameters '{"commands":[
-      #         "aws s3 cp s3://540034108652-devops-scripts/init.py /tmp/init.py",
-      #         "python3 /tmp/init.py || exit 1",
-      #         "rm /tmp/init.py"
-      #       ]}' \
-      #       --query 'Command.CommandId' \
-      #       --output text \
-      #       --region eu-north-1)
-      #     echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT
+      - name: Initializing Database on RDS using Ec2
+        id: init
+        run: |
+          CMD_ID=$(aws ssm send-command \
+            --targets "Key=tag:App,Values=flask" \
+            --document-name "AWS-RunShellScript" \
+            --parameters '{"commands":[
+              "aws s3 cp s3://540034108652-devops-scripts/init.py /tmp/init.py",
+              "python3 /tmp/init.py || exit 1",
+              "rm /tmp/init.py"
+            ]}' \
+            --query 'Command.CommandId' \
+            --output text \
+            --region eu-north-1)
+          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT
 
-      # - name: Show Results
-      #   run: |
-      #     sleep 30
+      - name: Show Results
+        run: |
+          sleep 30
 
-      #     aws ssm list-command-invocations \
-      #       --command-id "${{ steps.init.outputs.cmd_id }}" \
-      #       --details \
-      #       --region eu-north-1 \
-      #       --output text
+          aws ssm list-command-invocations \
+            --command-id "${{ steps.init.outputs.cmd_id }}" \
+            --details \
+            --region eu-north-1 \
+            --output text
 
-      #     FAILED=$(aws ssm list-command-invocations \
-      #       --command-id "${{ steps.init.outputs.cmd_id }}" \
-      #       --query "length(CommandInvocations[?Status=='Failed'])" \
-      #       --output text \
-      #       --region eu-north-1)
+          FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{ steps.init.outputs.cmd_id }}" \
+            --query "length(CommandInvocations[?Status=='Failed'])" \
+            --output text \
+            --region eu-north-1)
 
-      #     [ "$FAILED" -gt 0 ] && \
-      #       echo "::error::Database Creation Failed $FAILED instance(s)!" && \
-      #       exit 1
-
-      #     echo "✅ Database Created Successfully"
+          [ "$FAILED" -gt 0 ] && \
+            echo "::error::Database Creation Failed $FAILED instance(s)!" && \
+            exit 1
diff --git a/.github/workflows/smoke_test.yml b/.github/workflows/smoke_test.yml
--- a/.github/workflows/smoke_test.yml
+++ b/.github/workflows/smoke_test.yml
@@ -1,7 +1,7 @@
 name: Smoke Testing For Infra and Networking
 
 on:
-  workflow_call:
+  workflow_dispatch:
 
 permissions:
   id-token: write
@@ -10,21 +10,21 @@ permissions:
 jobs:
   smoke:
     runs-on: ubuntu-latest
+
     steps:
       - uses: actions/checkout@v4
         with:
-          repository: annusingh1211/banking-app-2-tier
-          ref: main
+          repository:annusingh12112003/banking-app-2-tier
+
 
       - uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: arn:aws:iam::540034108652:role/github-action-deploy-role-cicd-new
           aws-region: eu-north-1
-
       - name: Upload smoke_test.py to S3
         run: |
-          aws s3 mb s3://540034108652-devops-scripts --region eu-north-1 2>/dev/null || true
-          aws s3 cp smoke_test.py s3://540034108652-devops-scripts/smoke_test.py --region eu-north-1
+        aws s3 mb s3://540034108652-devops-scripts --region eu-north-1 2>/dev/null || true
+        aws s3 cp smoke_test.py s3://540034108652-devops-scripts/smoke_test.py --region eu-north-1
 
       - name: Run Smoke Test on Fleet
         id: smoke
@@ -32,15 +32,18 @@ jobs:
           CMD_ID=$(aws ssm send-command \
             --targets "Key=tag:App,Values=flask" \
             --document-name "AWS-RunShellScript" \
-            --parameters '{"commands":[
-              "aws s3 cp s3://540034108652-devops-scripts/smoke_test.py /tmp/smoke_test.py",
-              "pip3 install pymysql -q 2>/dev/null",
-              "python3 /tmp/smoke_test.py || exit  1",
-              "rm /tmp/smoke_test.py"
-            ]}' \
+            --parameters '{
+              "commands":[
+                "aws s3 cp s3://540034108652-devops-scripts/smoke_test.py /tmp/smoke_test.py",
+                "pip3 install pymysql -q 2>/dev/null",
+                "python3 /tmp/smoke_test.py || exit 1",
+                "rm -f /tmp/smoke_test.py "
+              ]
+            }' \
             --query 'Command.CommandId' \
             --output text \
             --region eu-north-1)
+
           echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT
 
       - name: Show Results
@@ -50,8 +53,9 @@ jobs:
           aws ssm list-command-invocations \
             --command-id "${{ steps.smoke.outputs.cmd_id }}" \
             --details \
-            --region eu-north-1 \
-            --output text
+            --query "length(CommandInvocations[*].{Instance:InstanceId,Status:Status,output:CommandPlugins[0].Output}" \
+            --output table \
+            --region eu-north-1
 
           FAILED=$(aws ssm list-command-invocations \
             --command-id "${{ steps.smoke.outputs.cmd_id }}" \
@@ -59,8 +63,8 @@ jobs:
             --output text \
             --region eu-north-1)
 
-          [ "$FAILED" -gt 0 ] && \
-            echo "::error::Smoke test failed on $FAILED instance(s)!" && \
+          [ "$FAILED" -gt 0 ]; then
+            echo "::error::$FAILED instance(s) failed the smoke test."
             exit 1
 
           echo "✅ Smoke Test Passed"
